# Generated by Django 4.0.1 on 2022-03-13 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='last_sent_time',
        ),
    ]
